### ISSUE TITLE
add english-esperanto dictionary

### ISSUE THREAD

**Issue by andijh92** [freedict/fd-dictionaries#23]
Hello,

Please, can you add the ESPDIC (Esperanto-English Dictionary) from Paul Denisowski? The dictionary uses the CC BY 3.0 licence, has 63k words and is available in a machine friendly format. See http://www.denisowski.org/Esperanto/ESPDIC/espdic_readme.htm .
Thanks for your cool project!

Regards, Andy

**Comment by humenda** [comment]
Hi

Thanks a lot for pointing us at this free and open dictionary!

The text file looks as if it were really easy to parse. I'm don't have  a lot of
time ATM, but will have a look soon, I think. If anybody wants to pick up this
easy task (good for newcomers, too), please indicate this in this issue.

Thanks

**Comment by humenda** [comment]
I have a first working draft now. The dictionary markup is somewhat problematic,
because semantic and syntactic annotations are mixed. With a few lines patched
(around 80 modifications), I get a pretty nice dictionary. I'll try to get my
changes upstream or to preserve the patch and I'll probably push my changes to
our tools soon, so that the dictionary can be online in roughly 3-4 weeks.

**Comment by bansp** [comment]
I'm wonderfully tied up with stuff as usual, but if you'd like to discuss some markup options, Sebastian, please feel welcome to fire away.

**Comment by humenda** [comment]
@bansp Your help is appreciated, as long as I don't merge the code quicker :-).

One example would be:

`akuŝi : to (be in) labor, be in the process of giving birth`

"to labor" and "to be in labor" are two different things. Are the parenthesis a
sign to encode both forms or is it just to show a collocate? This question is
even harder to answer for a script, because usage hint like categories, etc. are
also enclosed in round parenthesis. Currently I do a bit of wild-guessing,
depending whether "be" or similar words are within the parenthesis.

**Comment by humenda** [comment]
Hi again,

I'm closing this issue. @andijh92, we have released trhe epo-eng dictionary.
There's currently a bug in the web site and therefore it is not yet downloaded
in the download overview. As a temporary work-around, it's in the XML API:
<http://freedict.com/freedict-database.xml>. If you find any mistakes, please
let me know and I'll look into it.

Cheers

**Comment by andijh92** [comment]
Thank you very much!
